var num1 = 10;
var num2 = 20;
var temp;
temp = num1; 
num1 = num2;
num2 = temp; 
console.log("after swapping");
console.log("num1 = "+ num1);
console.log("num2 =" + num2); 
// console.log("value of num1=" + num1, "and value of num2" + num2);